from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import FishSpecies

SAMPLE_FISH_SPECIES = [
    {
        "common_name": "Betta",
        "scientific_name": "Betta splendens",
        "description": "Colorful labyrinth fish often kept individually.",
        "ideal_temp_min": 24.0,
        "ideal_temp_max": 28.0,
        "ideal_ph_min": 6.5,
        "ideal_ph_max": 7.5,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 80.0,
        "ideal_tds_max": 250.0,
        "diet": "Carnivorous micropellets and occasional live food.",
        "compatibility_notes": "Best kept alone or in carefully managed setups.",
        "care_tips": "Avoid strong water flow and sudden temperature shifts.",
    },
    {
        "common_name": "Guppy",
        "scientific_name": "Poecilia reticulata",
        "description": "Hardy livebearer popular for community tanks.",
        "ideal_temp_min": 22.0,
        "ideal_temp_max": 28.0,
        "ideal_ph_min": 7.0,
        "ideal_ph_max": 8.0,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 150.0,
        "ideal_tds_max": 400.0,
        "diet": "Omnivorous flakes, pellets, and vegetable supplements.",
        "compatibility_notes": "Compatible with peaceful fish of similar size.",
        "care_tips": "Keep stable temperature and avoid overcrowding.",
    },
    {
        "common_name": "Goldfish",
        "scientific_name": "Carassius auratus",
        "description": "Cold-water carp species requiring high filtration.",
        "ideal_temp_min": 18.0,
        "ideal_temp_max": 24.0,
        "ideal_ph_min": 7.0,
        "ideal_ph_max": 8.0,
        "ideal_do_min": 6.0,
        "ideal_tds_min": 120.0,
        "ideal_tds_max": 350.0,
        "diet": "Sinking pellets with vegetable matter.",
        "compatibility_notes": "Best with other goldfish varieties.",
        "care_tips": "Maintain strong aeration and frequent partial water changes.",
    },
    {
        "common_name": "Koi",
        "scientific_name": "Cyprinus rubrofuscus",
        "description": "Large ornamental carp usually kept in ponds.",
        "ideal_temp_min": 18.0,
        "ideal_temp_max": 26.0,
        "ideal_ph_min": 7.0,
        "ideal_ph_max": 8.5,
        "ideal_do_min": 6.0,
        "ideal_tds_min": 100.0,
        "ideal_tds_max": 300.0,
        "diet": "Protein-rich pellets and seasonal supplements.",
        "compatibility_notes": "Requires large volumes and robust filtration.",
        "care_tips": "Monitor ammonia closely in heavily stocked setups.",
    },
    {
        "common_name": "Neon Tetra",
        "scientific_name": "Paracheirodon innesi",
        "description": "Small schooling fish with bright neon stripe.",
        "ideal_temp_min": 22.0,
        "ideal_temp_max": 26.0,
        "ideal_ph_min": 6.0,
        "ideal_ph_max": 7.0,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 50.0,
        "ideal_tds_max": 180.0,
        "diet": "Micro pellets and fine flakes.",
        "compatibility_notes": "Keep in groups of at least six.",
        "care_tips": "Avoid sudden changes in pH and temperature.",
    },
    {
        "common_name": "Angelfish",
        "scientific_name": "Pterophyllum scalare",
        "description": "Tall-bodied cichlid common in planted aquariums.",
        "ideal_temp_min": 24.0,
        "ideal_temp_max": 30.0,
        "ideal_ph_min": 6.5,
        "ideal_ph_max": 7.5,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 80.0,
        "ideal_tds_max": 220.0,
        "diet": "Omnivorous flakes, pellets, and frozen food.",
        "compatibility_notes": "Can be territorial when breeding.",
        "care_tips": "Provide vertical space and hiding spots.",
    },
    {
        "common_name": "Discus",
        "scientific_name": "Symphysodon aequifasciatus",
        "description": "Sensitive cichlid that requires pristine water.",
        "ideal_temp_min": 28.0,
        "ideal_temp_max": 31.0,
        "ideal_ph_min": 6.0,
        "ideal_ph_max": 7.0,
        "ideal_do_min": 6.0,
        "ideal_tds_min": 50.0,
        "ideal_tds_max": 150.0,
        "diet": "High-quality granules and frozen protein feed.",
        "compatibility_notes": "Best with peaceful warm-water tankmates.",
        "care_tips": "Maintain strict routine for water changes.",
    },
    {
        "common_name": "Molly",
        "scientific_name": "Poecilia sphenops",
        "description": "Hardy livebearer that tolerates varied conditions.",
        "ideal_temp_min": 24.0,
        "ideal_temp_max": 28.0,
        "ideal_ph_min": 7.2,
        "ideal_ph_max": 8.2,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 180.0,
        "ideal_tds_max": 450.0,
        "diet": "Omnivorous diet with algae-based food.",
        "compatibility_notes": "Peaceful but active, keep in groups.",
        "care_tips": "Supplement with plant matter to prevent bloating.",
    },
    {
        "common_name": "Platy",
        "scientific_name": "Xiphophorus maculatus",
        "description": "Community livebearer with many color variations.",
        "ideal_temp_min": 22.0,
        "ideal_temp_max": 27.0,
        "ideal_ph_min": 7.0,
        "ideal_ph_max": 8.2,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 150.0,
        "ideal_tds_max": 350.0,
        "diet": "Balanced omnivorous pellet and flake diet.",
        "compatibility_notes": "Generally peaceful and beginner-friendly.",
        "care_tips": "Keep a balanced male-to-female ratio.",
    },
    {
        "common_name": "Swordtail",
        "scientific_name": "Xiphophorus hellerii",
        "description": "Active livebearer known for elongated tail fin.",
        "ideal_temp_min": 22.0,
        "ideal_temp_max": 28.0,
        "ideal_ph_min": 7.0,
        "ideal_ph_max": 8.4,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 150.0,
        "ideal_tds_max": 400.0,
        "diet": "Omnivorous flakes and small pellets.",
        "compatibility_notes": "Active swimmers requiring open tank space.",
        "care_tips": "Avoid housing multiple dominant males in small tanks.",
    },
    {
        "common_name": "Corydoras Catfish",
        "scientific_name": "Corydoras aeneus",
        "description": "Peaceful bottom-dweller and scavenger species.",
        "ideal_temp_min": 22.0,
        "ideal_temp_max": 27.0,
        "ideal_ph_min": 6.0,
        "ideal_ph_max": 7.5,
        "ideal_do_min": 5.5,
        "ideal_tds_min": 60.0,
        "ideal_tds_max": 200.0,
        "diet": "Sinking wafers and occasional protein treats.",
        "compatibility_notes": "Should be kept in groups.",
        "care_tips": "Use smooth substrate to protect barbels.",
    },
    {
        "common_name": "Zebra Danio",
        "scientific_name": "Danio rerio",
        "description": "Fast schooling fish suited for beginner tanks.",
        "ideal_temp_min": 20.0,
        "ideal_temp_max": 26.0,
        "ideal_ph_min": 6.5,
        "ideal_ph_max": 7.5,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 70.0,
        "ideal_tds_max": 220.0,
        "diet": "Small flakes and micropellets.",
        "compatibility_notes": "Very active, keep in schools.",
        "care_tips": "Provide moderate flow and open swimming lanes.",
    },
    {
        "common_name": "Oscar",
        "scientific_name": "Astronotus ocellatus",
        "description": "Large intelligent cichlid with high bioload.",
        "ideal_temp_min": 24.0,
        "ideal_temp_max": 28.0,
        "ideal_ph_min": 6.5,
        "ideal_ph_max": 7.5,
        "ideal_do_min": 6.0,
        "ideal_tds_min": 100.0,
        "ideal_tds_max": 250.0,
        "diet": "Large pellets and occasional protein foods.",
        "compatibility_notes": "Requires large tank and robust filtration.",
        "care_tips": "Monitor ammonia and nitrite closely due to heavy waste.",
    },
    {
        "common_name": "Cherry Barb",
        "scientific_name": "Puntius titteya",
        "description": "Small peaceful barb with red coloration.",
        "ideal_temp_min": 23.0,
        "ideal_temp_max": 27.0,
        "ideal_ph_min": 6.0,
        "ideal_ph_max": 7.5,
        "ideal_do_min": 5.0,
        "ideal_tds_min": 60.0,
        "ideal_tds_max": 180.0,
        "diet": "Omnivorous fine flakes and micro food.",
        "compatibility_notes": "Good community fish when kept in schools.",
        "care_tips": "Include plants to reduce stress and improve color.",
    },
    {
        "common_name": "Clownfish",
        "scientific_name": "Amphiprion ocellaris",
        "description": "Marine species included as reference entry.",
        "ideal_temp_min": 24.0,
        "ideal_temp_max": 27.0,
        "ideal_ph_min": 8.0,
        "ideal_ph_max": 8.4,
        "ideal_do_min": 6.0,
        "ideal_tds_min": 30000.0,
        "ideal_tds_max": 36000.0,
        "diet": "Marine pellets and frozen marine mix.",
        "compatibility_notes": "Requires marine system and stable salinity.",
        "care_tips": "Track salinity and pH tightly in marine setups.",
    },
]


def seed_fish_species(db: Session) -> int:
    created = 0
    existing_names = set(db.scalars(select(FishSpecies.common_name)).all())

    for fish_data in SAMPLE_FISH_SPECIES:
        if fish_data["common_name"] in existing_names:
            continue
        db.add(FishSpecies(**fish_data))
        created += 1

    return created
