import 'package:aqualogic/features/fish/models/fish_species.dart';
import 'package:aqualogic/features/tanks/models/tank_info.dart';
import 'package:aqualogic/shared/models/aqualogic_status.dart';

class DemoData {
  static const tanks = [
    TankInfo(
      id: 'display-reef-a',
      initial: 'D',
      name: 'Display Reef A',
      subtitle: 'Marine display · 320L',
      status: 'NORMAL',
      typeLabel: 'Mixed reef',
      volumeLabel: '320L',
      lastFedLabel: '2h ago',
      description: 'Primary display tank with mixed coral and reef fish.',
      locationLabel: 'Main room',
      lastReportLabel: 'Updated just now',
      latestCondition: 'All installed readings are within configured ranges.',
      monitoringLabel: 'Reporting normally',
      readings: [
        TankReading(
          parameter: SensorParameter.temperature,
          value: '26.8',
          unit: '°C',
          condition: ReadingCondition.normal,
          timestampLabel: 'Just now',
        ),
        TankReading(
          parameter: SensorParameter.ph,
          value: '8.2',
          unit: 'pH',
          condition: ReadingCondition.normal,
          timestampLabel: 'Just now',
        ),
        TankReading(
          parameter: SensorParameter.turbidity,
          value: '2,620',
          unit: 'raw',
          condition: ReadingCondition.normal,
          timestampLabel: 'Just now',
        ),
        TankReading(
          parameter: SensorParameter.tds,
          value: '1,080',
          unit: 'ppm',
          condition: ReadingCondition.normal,
          timestampLabel: 'Just now',
        ),
      ],
      species: [
        TankSpeciesSummary(
          speciesId: 'ocellaris-clownfish',
          name: 'Ocellaris Clownfish',
          suitability: SpeciesSuitability.suitable,
        ),
        TankSpeciesSummary(
          speciesId: 'yellow-tang',
          name: 'Yellow Tang',
          suitability: SpeciesSuitability.suitable,
        ),
      ],
      equipmentCount: 4,
      recentActivity: [
        TankActivity(
          id: 'reef-feed',
          title: 'Feeding completed',
          detail: 'Routine feed cycle',
          timeLabel: '8:30 AM',
        ),
        TankActivity(
          id: 'reef-uv',
          title: 'UV cycle completed',
          detail: 'Scheduled cycle',
          timeLabel: '7:45 AM',
        ),
      ],
      isSelected: true,
    ),
    TankInfo(
      id: 'quarantine-b',
      initial: 'Q',
      name: 'Quarantine B',
      subtitle: 'Quarantine · 80L',
      status: 'WARNING',
      typeLabel: 'Quarantine',
      volumeLabel: '80L',
      lastFedLabel: '4h ago',
      description: 'Observation tank for new or recovering livestock.',
      locationLabel: 'Treatment room',
      lastReportLabel: 'Last report 1 min ago',
      latestCondition: 'pH requires attention.',
      monitoringLabel: 'Reporting normally',
      readings: [
        TankReading(
          parameter: SensorParameter.temperature,
          value: '25.9',
          unit: '°C',
          condition: ReadingCondition.normal,
          timestampLabel: '1 min ago',
        ),
        TankReading(
          parameter: SensorParameter.ph,
          value: '8.1',
          unit: 'pH',
          condition: ReadingCondition.warning,
          timestampLabel: '1 min ago',
          note: 'Outside the configured quarantine range.',
        ),
        TankReading(
          parameter: SensorParameter.turbidity,
          value: '2,340',
          unit: 'raw',
          condition: ReadingCondition.normal,
          timestampLabel: '1 min ago',
        ),
        TankReading(
          parameter: SensorParameter.tds,
          value: '1,420',
          unit: 'ppm',
          condition: ReadingCondition.normal,
          timestampLabel: '1 min ago',
        ),
      ],
      issues: [
        TankIssue(
          id: 'quarantine-ph',
          category: TankIssueCategory.waterQuality,
          severity: TankIssueSeverity.warning,
          title: 'pH requires attention',
          message: 'pH is outside the configured quarantine range.',
          timeLabel: 'Started 6 min ago',
          lifecycle: TankIssueLifecycle.active,
        ),
      ],
      species: [
        TankSpeciesSummary(
          speciesId: 'ocellaris-clownfish',
          name: 'Ocellaris Clownfish',
          suitability: SpeciesSuitability.attention,
        ),
      ],
      equipmentCount: 3,
      recentActivity: [
        TankActivity(
          id: 'quarantine-check',
          title: 'Tank check recorded',
          detail: 'Routine quarantine round',
          timeLabel: '8:12 AM',
        ),
      ],
    ),
    TankInfo(
      id: 'freshwater-c',
      initial: 'F',
      name: 'Freshwater C',
      subtitle: 'Freshwater display · 240L',
      status: 'CRITICAL',
      typeLabel: 'Freshwater',
      volumeLabel: '240L',
      lastFedLabel: '1h ago',
      description: 'Warm freshwater tank tuned for discus stability.',
      locationLabel: 'Freshwater room',
      lastReportLabel: 'Last report 45 sec ago',
      latestCondition: 'TDS is outside the configured range.',
      monitoringLabel: 'Reporting normally',
      readings: [
        TankReading(
          parameter: SensorParameter.temperature,
          value: '29.4',
          unit: '°C',
          condition: ReadingCondition.normal,
          timestampLabel: '45 sec ago',
        ),
        TankReading(
          parameter: SensorParameter.ph,
          value: '6.8',
          unit: 'pH',
          condition: ReadingCondition.normal,
          timestampLabel: '45 sec ago',
        ),
        TankReading(
          parameter: SensorParameter.turbidity,
          value: '2,180',
          unit: 'raw',
          condition: ReadingCondition.normal,
          timestampLabel: '45 sec ago',
        ),
        TankReading(
          parameter: SensorParameter.tds,
          value: '2,370',
          unit: 'ppm',
          condition: ReadingCondition.critical,
          timestampLabel: '45 sec ago',
          note: 'Outside the configured freshwater range.',
        ),
      ],
      issues: [
        TankIssue(
          id: 'freshwater-tds',
          category: TankIssueCategory.waterQuality,
          severity: TankIssueSeverity.critical,
          title: 'Critical TDS reading',
          message: 'TDS is outside the configured range.',
          timeLabel: 'Started 18 min ago',
          lifecycle: TankIssueLifecycle.active,
        ),
      ],
      species: [
        TankSpeciesSummary(
          speciesId: 'discus',
          name: 'Discus',
          suitability: SpeciesSuitability.attention,
        ),
      ],
      equipmentCount: 4,
      recentActivity: [
        TankActivity(
          id: 'freshwater-feed',
          title: 'Feeding completed',
          detail: 'Routine feed cycle',
          timeLabel: '8:05 AM',
        ),
      ],
    ),
    TankInfo(
      id: 'nursery-d',
      initial: 'N',
      name: 'Nursery D',
      subtitle: 'Nursery · 60L',
      status: 'NORMAL',
      typeLabel: 'Nursery',
      volumeLabel: '60L',
      lastFedLabel: '30m ago',
      description: 'Small nursery tank for fry and gentle flow.',
      locationLabel: 'Propagation room',
      lastReportLabel: 'Last report 3 min ago',
      latestCondition: 'Ready for routine checks.',
      monitoringLabel: 'Reporting normally',
      readings: [
        TankReading(
          parameter: SensorParameter.temperature,
          value: '25.1',
          unit: '°C',
          condition: ReadingCondition.normal,
          timestampLabel: '3 min ago',
        ),
        TankReading(
          parameter: SensorParameter.ph,
          value: '7.2',
          unit: 'pH',
          condition: ReadingCondition.normal,
          timestampLabel: '3 min ago',
        ),
        TankReading(
          parameter: SensorParameter.turbidity,
          value: '2,280',
          unit: 'raw',
          condition: ReadingCondition.normal,
          timestampLabel: '3 min ago',
        ),
        TankReading(
          parameter: SensorParameter.tds,
          value: '620',
          unit: 'ppm',
          condition: ReadingCondition.normal,
          timestampLabel: '3 min ago',
        ),
      ],
      species: [
        TankSpeciesSummary(
          speciesId: 'guppy',
          name: 'Guppy',
          suitability: SpeciesSuitability.suitable,
        ),
      ],
      equipmentCount: 2,
      recentActivity: [],
    ),
  ];

  static const fishLibrary = [
    FishSpecies(
      id: 'discus',
      name: 'Discus',
      scientificName: 'Symphysodon aequifasciatus',
      type: 'FRESHWATER',
      temperatureRange: '28-31 °C',
      phRange: '6.0-7.0',
      tdsRange: '50-250 ppm',
      diet: 'High-quality pellets, flakes, and frozen foods',
      description:
          'A warm-water cichlid that benefits from stable, clean, soft water.',
      careNote: 'Warm, soft, stable water; sensitive to sudden changes.',
      careGroup: 'Warm freshwater',
      compatibilityNote: 'Choose peaceful, similarly warm community species.',
    ),
    FishSpecies(
      id: 'guppy',
      name: 'Guppy',
      scientificName: 'Poecilia reticulata',
      type: 'FRESHWATER',
      temperatureRange: '22-28 °C',
      phRange: '6.8-7.8',
      tdsRange: '150-400 ppm',
      diet: 'Omnivore; flakes, pellets, and occasional live foods',
      description: 'A hardy livebearer suited to stable community aquariums.',
      careNote: 'Hardy community fish; avoid overcrowding and poor filtration.',
      careGroup: 'Community freshwater',
      compatibilityNote:
          'Monitor population growth and fin-nipping tank mates.',
    ),
    FishSpecies(
      id: 'neon-tetra',
      name: 'Neon Tetra',
      scientificName: 'Paracheirodon innesi',
      type: 'FRESHWATER',
      temperatureRange: '20-26 °C',
      phRange: '6.0-7.0',
      tdsRange: '50-200 ppm',
      diet: 'Small flakes, micro pellets, and frozen foods',
      description: 'A schooling fish that prefers gentle flow and cover.',
      careNote: 'Best kept in groups with gentle flow and dimmer lighting.',
      careGroup: 'Community freshwater',
      compatibilityNote:
          'Keep in a group and avoid large predatory tank mates.',
    ),
    FishSpecies(
      id: 'ocellaris-clownfish',
      name: 'Ocellaris Clownfish',
      scientificName: 'Amphiprion ocellaris',
      type: 'SALTWATER',
      temperatureRange: '24-27 °C',
      phRange: '8.1-8.4',
      tdsRange: 'Not used for marine suitability',
      diet: 'Marine pellets, algae-based foods, and frozen foods',
      description: 'A resilient marine fish that still needs stable salinity.',
      careNote: 'Stable salinity and clean marine water are more important.',
      careGroup: 'Marine community',
      compatibilityNote:
          'Provide territory and introduce compatible tank mates.',
    ),
    FishSpecies(
      id: 'yellow-tang',
      name: 'Yellow Tang',
      scientificName: 'Zebrasoma flavescens',
      type: 'SALTWATER',
      temperatureRange: '24-27 °C',
      phRange: '8.1-8.4',
      tdsRange: 'Not used for marine suitability',
      diet: 'Marine algae, nori, and herbivore pellets',
      description: 'An active herbivore that needs swimming space and grazing.',
      careNote: 'Needs strong filtration, swimming space, and algae grazing.',
      careGroup: 'Marine herbivore',
      compatibilityNote:
          'Plan territory carefully when keeping multiple tangs.',
    ),
    FishSpecies(
      id: 'betta',
      name: 'Betta',
      scientificName: 'Betta splendens',
      type: 'FRESHWATER',
      temperatureRange: '24-30 °C',
      phRange: '6.5-7.5',
      tdsRange: '50-300 ppm',
      diet: 'Carnivorous pellets and small frozen foods',
      description:
          'A warm-water fish that prefers calm flow and resting cover.',
      careNote: 'Prefers warm, calm water and low-stress tank mates.',
      careGroup: 'Warm freshwater',
      compatibilityNote: 'Avoid fin-nipping species and crowded conditions.',
    ),
  ];
}
